###
POST  http://localhost:3000
content-type: application/json

{
  "title": "1984",
  "author": "George Orwell"
}

###
GET  http://localhost:3000
content-type: application/json

###
GET  http://localhost:3000/
content-type: application/json

###
DELETE http://localhost:3000
content-type: application/json

###
DELETE http://localhost:3000/6643a40ac704d9410af231bd
content-type: application/json
